apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: adservice
  namespace: boutique
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: adservice
  targetCPUUtilizationPercentage: 35
  
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cartservice
  namespace: boutique
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cartservice
  targetCPUUtilizationPercentage: 35

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: checkoutservice
  namespace: boutique
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: checkoutservice
  targetCPUUtilizationPercentage: 35

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: currencyservice
  namespace: boutique
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: currencyservice
  targetCPUUtilizationPercentage: 35

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: emailservice
  namespace: boutique
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: emailservice
  targetCPUUtilizationPercentage: 35

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend
  namespace: boutique
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  targetCPUUtilizationPercentage: 35

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: paymentservice
  namespace: boutique
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: paymentservice
  targetCPUUtilizationPercentage: 35

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: productcatalogservice
  namespace: boutique
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: productcatalogservice
  targetCPUUtilizationPercentage: 35

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: recommendationservice
  namespace: boutique
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: recommendationservice
  targetCPUUtilizationPercentage: 35

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: redis-cart
  namespace: boutique
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: redis-cart
  targetCPUUtilizationPercentage: 35

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: shippingservice
  namespace: boutique
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shippingservice
  targetCPUUtilizationPercentage: 35

